# Generated by Django 5.0 on 2024-01-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admineapp', '0002_admin_password_admin_username_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='ttmadmin_table',
        ),
    ]
