# Generated by Django 5.0 on 2024-01-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admineapp', '0003_alter_admin_password_alter_admin_username_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='sujal',
        ),
    ]
