# Generated by Django 5.0 on 2024-02-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admineapp', '0010_alter_register_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register_table',
        ),
    ]
