# Generated by Django 5.0 on 2024-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admineapp', '0011_alter_register_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='phno',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
