# Generated by Django 5.0 on 2024-02-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admineapp', '0012_alter_register_password_alter_register_phno'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register1_table',
        ),
    ]
